// Genre, mood, and warning constants for AddBookModal and related components

export const COMMON_WARNINGS = [
  'Sexual Content',
  'Abuse',
  'Death',
  'Substance Use',
  'Language',
  'Other',
];

export const COMMON_MOODS = [
  'Cozy',
  'Dark',
  'Funny',
  'Adventurous',
  'Emotional',
  'Inspiring',
  'Steamy',
  'Chilling',
  'Feel-Good',
  'Heartbreaking',
  'Other',
];

export const GENRES = [
  {
    value: 'romance',
    label: 'Romance',
    subGenres: [
      'Contemporary',
      'Historical',
      'Paranormal',
      'Gothic Romance',
      'Romantic Comedy',
      'Romantic Suspense',
      'Fantasy Romance',
      'LGBTQ+',
      'Dark Romance',
      'Erotica',
      'Regency',
      'Sports',
      'Military',
      'Billionaire',
      'New Adult',
      'Young Adult',
      'Clean & Wholesome',
      'Reverse Harem',
      'Friends to Lovers',
      'Enemies to Lovers',
      'Second Chance',
      'Marriage of Convenience',
      'Secret Baby',
      'Small Town',
      'Royalty',
      'Rock Star',
      'Office Romance',
      'Age Gap',
      'Forbidden Love',
      'Slow Burn',
      'Alpha Male',
      'Arranged Marriage',
      'Amnesia',
      'Fake Relationship',
      'Holiday Romance',
      'Medical Romance',
      'Sports Romance',
      'Other',
    ],
  },
  {
    value: 'fantasy',
    label: 'Fantasy',
    subGenres: [
      'Epic Fantasy',
      'Urban Fantasy',
      'Dark Fantasy',
      'Paranormal',
      'Sword & Sorcery',
      'Fairy Tale',
      'Mythic',
      'Romantic Fantasy',
      'Other',
    ],
  },
  {
    value: 'science_fiction',
    label: 'Science Fiction',
    subGenres: [
      'Dystopian',
      'Space Opera',
      'Cyberpunk',
      'Time Travel',
      'Alien',
      'Post-Apocalyptic',
      'Hard Sci-Fi',
      'Soft Sci-Fi',
      'Other',
    ],
  },
  {
    value: 'mystery',
    label: 'Mystery & Thriller',
    subGenres: [
      'Cozy Mystery',
      'Detective',
      'Crime',
      'Police Procedural',
      'Legal Thriller',
      'Psychological Thriller',
      'Noir',
      'Suspense',
      'Other',
    ],
  },
  {
    value: 'horror',
    label: 'Horror',
    subGenres: [
      'Gothic',
      'Paranormal',
      'Supernatural',
      'Occult',
      'Slasher',
      'Monster',
      'Psychological',
      'Other',
    ],
  },
  {
    value: 'historical',
    label: 'Historical',
    subGenres: [
      'Historical Fiction',
      'Historical Romance',
      'Biographical',
      'War',
      'Other',
    ],
  },
  {
    value: 'literary',
    label: 'Literary Fiction',
    subGenres: ['Coming of Age', 'Family Saga', 'Satire', 'Drama', 'Other'],
  },
  {
    value: 'young_adult',
    label: 'Young Adult',
    subGenres: [
      'Contemporary YA',
      'YA Fantasy',
      'YA Romance',
      'YA Dystopian',
      'YA Mystery',
      'Other',
    ],
  },
  {
    value: 'children',
    label: "Children's",
    subGenres: [
      'Picture Book',
      'Early Reader',
      'Middle Grade',
      'Chapter Book',
      'Other',
    ],
  },
  {
    value: 'graphic_novel',
    label: 'Graphic Novel & Manga',
    subGenres: [
      'Manga',
      'Webtoon',
      'Superhero',
      'Slice of Life',
      'Fantasy',
      'Other',
    ],
  },
  {
    value: 'nonfiction',
    label: 'Nonfiction',
    subGenres: [
      'Memoir',
      'Biography',
      'Self-Help',
      'True Crime',
      'History',
      'Science',
      'Psychology',
      'Business',
      'Health & Wellness',
      'Cookbook',
      'Travel',
      'Essay',
      'Politics',
      'Religion & Spirituality',
      'Parenting',
      'Education',
      'Other',
    ],
  },
  {
    value: 'poetry',
    label: 'Poetry',
    subGenres: ['Contemporary', 'Classic', 'Epic', 'Haiku', 'Other'],
  },
  {
    value: 'other',
    label: 'Other',
    subGenres: ['Other'],
  },
];
